### ISSUE TITLE
Cannot Install Messanger Pro App , android 8

### ISSUE THREAD

**Issue by KorontosTheThird** [Mino260806/MessengerPro#38]
as the title says , i cannot install the messenger app whatever i do , i have an android 8 phone so could that be the issue ?
(i can install mpro app with no problems)

EDIT : it turns out , the lollipop apks are swapped , i mean the root version is named nonroot and the nonroot is labeled only "messenger416-lollipop.apk"

**Comment by Mino260806** [comment]
I think you don't understand what's the difference between "-noroot" and the ones without suffix.
The apks ending with "noroot" are patched messenger apks, which will allow the apk to communicate with the mod.
As for the apks without suffix, those are bare messenger apks, like when downloaded from google play, because the root users can have the app patched without being modified
