### ISSUE TITLE
/ud *[suggestion]

### ISSUE THREAD

**Issue by Joeeeeb5** [Mino260806/MessengerPro#48]
Add a command to search Urban Dictionary instead of the current one. It doesn't work sometimes and doesn't have the definition of a lot of words

**Comment by Mino260806** [comment]
Link a free and official api to the desired command and I'll reopen the issue

**Comment by Joeeeeb5** [comment]
here's one - https://medium.com/@kristian_io/generating-speech-audio-from-large-texts-using-api-free-f93df1a86f6a

Alternatively, you can use the Google speech synthesis (i think that's what it's called) that powers text-to-speech stuff to natively create the tts audio

**Comment by Joeeeeb5** [comment]
This is the one I found - https://rapidapi.com/community/api/urban-dictionary 
it's unofficial but works well and even got implemented as a messenger command in the mpro fork made by Loukious

**Comment by Mino260806** [comment]
> it's unofficial but works well
Anything unofficial might work well but can unexpectedly stop working at any time... Anyway the fork by Loukious is going to be merged so it will be included but keep in mind that it might break.
Anyway I will not reopen the issue because it's already implemented. 
Thanks for taking the time to research on the topic.
